Magdiel/boo 12 12  intro to nextjs
gmz2091/dooper-bootcamp pull request #2
Opened 2022-04-08 02:06 UTC by gmz2091

https://linear.app/dooper/issue/BOO-12/12-intro-to-nextjs

2022-04-08 15:07 UTC, ferpintado requested changes

2022-04-08 15:07 UTC, ferpintado commented on src/components/Navb/Navbar.tsx
> +const pagesRoues = [
corregir por `pageRoutes` para tener un nombre significativo

2022-04-08 15:07 UTC, ferpintado commented on src/components/Navb/Navbar.tsx
> +              sx={{ mr: 2, display: { xs: 'none', md: 'flex' } }}
Como se menciona en el README, preferimos usar styled components (revisar styles.tsx) para definir estilos. en este caso tambien el componente `<Typography>` acepta propiedades de espaciado `mr`

2022-04-08 15:07 UTC, ferpintado commented on src/components/Navb/styles.tsx
> +export const Element = styled('div')`
Asi es como se crea un styled component

2022-04-08 15:07 UTC, ferpintado commented on src/components/layouts/Layout.tsx
> +      <Box sx={{ padding: '10px 20px' }}>{children}</Box>
en ves de usar `sx` podemos usar `padding="10px 20px"` directamente en el `<Box>`

2022-04-11 05:05 UTC, stobar93 commented on src/components/Navb/Navbar.tsx
> +              aria-label="account of current user"
Podrias adaptar un poco este codigo para que sea representativo del uso que le quieres dar. Por ejemplo poner `aria-label='toggle menu button`

2022-04-11 05:05 UTC, stobar93 commented on src/components/Navb/Navbar.tsx
> +              aria-label="account of current user"
Los ejemplos de MUI vienen un poco genéricos y en algunos casos tienen cosas que pueden no ser necesarias segun la aplicación

2022-04-11 05:05 UTC, stobar93 commented on src/components/Navb/Navbar.tsx
> +              sx={{
Para mejorar la reusabilidad del codigo te sugiero modularizar un poco y talvez usar un hook de media query para definir cuando se muestra el menu o la appbar en lugar de usar el sx alternando el display

2022-04-11 05:05 UTC, stobar93 commented on src/components/Navb/Navbar.tsx
> +              sx={{
Tambien al modularizar este componente creo que puedes eliminar el sx en los hijos ya que con ocultar el componente padre bastaría

2022-04-18 16:13 UTC, JustinoTorreblanca approved these changes
Buen uso del Drawer y componentes de de MUI,  al hacer mi Header igual pensaba implementarlo pero preferí hacerlo a mi gusto y editarlo como yo quiera.

Otra observación: recuerdo haber leído sobre UX que en un Header cuando no hay mucho espacio usar Hamburguer Menu (Mobile) y cuando hay espacio (Laptop or Desktop) es mejor colocar las opciones de navegación con texto, es decir: Login    Register     Profile.
Al final es cuestión de gustos, pero qué opinas @ferpintado

2022-04-20 00:23 UTC, ferpintado approved these changes

2022-04-20 00:23 UTC, ferpintado commented on src/components/DrawerMenu/styles.tsx
> +import { styled } from '@mui/material'
Este archivo es opcional, si no llegaramos a necesitarlo podemos borrarlo

2022-04-20 00:41 UTC, stobar93 approved these changes

2022-04-20 01:06 UTC, merged